### ISSUE TITLE
GitHub auth seems to expire after being away

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#93]
After reloading a GitHub project in Editor, we get the message "the auth token has expired" (or a similar message -- I forgot to capture a screenshot). This seems to happen after being away from the editor for >24 hours (roughly?). It can be fixed by refreshing.

Next time it happens I'll take a screenshot.

**Comment by Zoramite** [comment]
Yeah, let me know if you see it again, it is supposed to refresh the cert, but if that is not working we need to update it to correctly auto refresh.

**Comment by jeremydw** [comment]
Here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/646525/125972561-a1d2e54b-b65f-497f-9071-49a3c5b3a1a9.png)

**Comment by jeremydw** [comment]
Traceback from the Cloud Run logs:

```
2021-07-16T15:32:49.070655Z POST 500 1.12 KiB 530 ms Chrome 91 https://api.beta.editor.dev/gh/blinkk/[]/test/project.get E  POST 500 1.12 KiB 530 ms Chrome 91
2021-07-16T15:32:49.069237Z } A 
2021-07-16T15:32:49.069228Z   } A 
2021-07-16T15:32:49.069221Z     } A 
2021-07-16T15:32:49.069213Z       uri: 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code' A 
2021-07-16T15:32:49.069202Z       error: 'bad_refresh_token', A 
2021-07-16T15:32:49.069194Z     details: { A 
2021-07-16T15:32:49.069187Z     description: 'The refresh token passed is incorrect or expired.', A 
2021-07-16T15:32:49.069175Z     message: 'Unable to refresh authentication with GitHub.', A 
2021-07-16T15:32:49.069166Z   apiError: { A 
2021-07-16T15:32:49.069158Z     at processTicksAndRejections (internal/process/task_queues.js:95:5) { A 
2021-07-16T15:32:49.069149Z     at authenticateGithub (/usr/src/app/dist/auth/githubAuth.js:117:9) A 
2021-07-16T15:32:49.069141Z     at verifyAuthResponse (/usr/src/app/dist/auth/githubAuth.js:135:15) A 
2021-07-16T15:32:49.069131Z     at new GenericApiError (/usr/src/app/dist/api/api.js:14:22) A 
2021-07-16T15:32:49.069111Z Error A 
2021-07-16T15:32:49.068304Z } A 
2021-07-16T15:32:49.068298Z   } A 
2021-07-16T15:32:49.068291Z     } A 
2021-07-16T15:32:49.068280Z       uri: 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code' A 
2021-07-16T15:32:49.068270Z       error: 'bad_refresh_token', A 
2021-07-16T15:32:49.068263Z     details: { A 
2021-07-16T15:32:49.068257Z     description: 'The refresh token passed is incorrect or expired.', A 
2021-07-16T15:32:49.068250Z     message: 'Unable to refresh authentication with GitHub.', A 
2021-07-16T15:32:49.068242Z   apiError: { A 
2021-07-16T15:32:49.068236Z     at processTicksAndRejections (internal/process/task_queues.js:95:5) { A 
2021-07-16T15:32:49.068228Z     at authenticateGithub (/usr/src/app/dist/auth/githubAuth.js:117:9) A 
2021-07-16T15:32:49.068222Z     at verifyAuthResponse (/usr/src/app/dist/auth/githubAuth.js:135:15) A 
2021-07-16T15:32:49.068214Z     at new GenericApiError (/usr/src/app/dist/api/api.js:14:22) A 
2021-07-16T15:32:49.068196Z Error A 
```

**Comment by jeremydw** [comment]
Not sure if this is a red herring but I found this when searching Google the same error -- https://github.community/t/bad-refresh-token-when-refreshing-an-user-to-server-token/126700/17

**Comment by jeremydw** [comment]
Got a similar error upon refreshing later... was resolved by refreshing.

![image](https://user-images.githubusercontent.com/646525/126056693-2a7acdfd-eeb5-4324-ac30-f8c73a0ed3b5.png)

```
2021-07-18T05:20:25.322042Z POST 500 885 B 768 ms Chrome 91 https://api.beta.editor.dev/gh/blinkk/[]/test/workspace.get E  POST 500 885 B 768 ms Chrome 91
2021-07-18T05:20:25.317406Z     at async GithubApi.getWorkspace (/usr/src/app/dist/api/githubApi.js:356:32) A 
2021-07-18T05:20:25.317397Z     at processTicksAndRejections (internal/process/task_queues.js:95:5) A 
2021-07-18T05:20:25.317387Z     at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:86:21 A 
2021-07-18T05:20:25.317380Z HttpError: Bad credentials A 
2021-07-18T05:20:25.317362Z } A 
2021-07-18T05:20:25.317353Z   } A 
2021-07-18T05:20:25.317343Z     request: { hook: [Function: bound bound register] } A 
2021-07-18T05:20:25.317331Z     }, A 
2021-07-18T05:20:25.317323Z       authorization: 'token [REDACTED]' A 
2021-07-18T05:20:25.317315Z       'user-agent': 'octokit-core.js/3.5.1 Node.js/14.17.3 (linux; x64)', A 
2021-07-18T05:20:25.317307Z       accept: 'application/vnd.github.v3+json', A 
2021-07-18T05:20:25.317300Z     headers: { A 
2021-07-18T05:20:25.317292Z     url: 'https://api.github.com/repos/blinkk/[]/branches/workspace%2Ftest', A 
2021-07-18T05:20:25.317283Z     method: 'GET', A 
2021-07-18T05:20:25.317275Z   request: { A 
2021-07-18T05:20:25.317266Z   }, A 
2021-07-18T05:20:25.317258Z     } A 
2021-07-18T05:20:25.317249Z       documentation_url: 'https://docs.github.com/rest' A 
2021-07-18T05:20:25.317240Z       message: 'Bad credentials', A 
2021-07-18T05:20:25.317231Z     data: { A 
2021-07-18T05:20:25.317223Z     }, A 
2021-07-18T05:20:25.317215Z       'x-xss-protection': '0' A 
2021-07-18T05:20:25.317206Z       'x-ratelimit-used': '1', A 
2021-07-18T05:20:25.317197Z       'x-ratelimit-resource': 'core', A 
2021-07-18T05:20:25.317184Z       'x-ratelimit-reset': '1626589225', A 
2021-07-18T05:20:25.317177Z       'x-ratelimit-remaining': '59', A 
2021-07-18T05:20:25.317170Z       'x-ratelimit-limit': '60', A 
2021-07-18T05:20:25.317161Z       'x-github-request-id': 'CBA1:6370:2295A5:DA04BF:60F3BA19', A 
2021-07-18T05:20:25.317153Z       'x-github-media-type': 'github.v3; format=json', A 
2021-07-18T05:20:25.317144Z       'x-frame-options': 'deny', A 
2021-07-18T05:20:25.317136Z       'x-content-type-options': 'nosniff', A 
2021-07-18T05:20:25.317128Z       vary: 'Accept-Encoding, Accept, X-Requested-With', A 
2021-07-18T05:20:25.317118Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', A 
2021-07-18T05:20:25.317107Z       server: 'GitHub.com', A 
2021-07-18T05:20:25.317099Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', A 
2021-07-18T05:20:25.317090Z       date: 'Sun, 18 Jul 2021 05:20:25 GMT', A 
2021-07-18T05:20:25.317083Z       'content-type': 'application/json; charset=utf-8', A 
2021-07-18T05:20:25.317075Z       'content-security-policy': "default-src 'none'", A 
2021-07-18T05:20:25.317067Z       'content-length': '80', A 
2021-07-18T05:20:25.317062Z       connection: 'close', A 
2021-07-18T05:20:25.317054Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', A 
2021-07-18T05:20:25.317039Z       'access-control-allow-origin': '*', A 
2021-07-18T05:20:25.317031Z     headers: { A 
2021-07-18T05:20:25.317023Z     status: 401, A 
2021-07-18T05:20:25.317016Z     url: 'https://api.github.com/repos/blinkk/[]/branches/workspace%2Ftest', A 
2021-07-18T05:20:25.317006Z   response: { A 
2021-07-18T05:20:25.316999Z   status: 401, A 
2021-07-18T05:20:25.316992Z     at async GithubApi.getWorkspace (/usr/src/app/dist/api/githubApi.js:356:32) { A 
2021-07-18T05:20:25.316980Z     at processTicksAndRejections (internal/process/task_queues.js:95:5) A 
2021-07-18T05:20:25.316969Z     at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:86:21 A 
2021-07-18T05:20:25.316922Z RequestError [HttpError]: Bad credentials A 
```

**Comment by Zoramite** [comment]
The auth timeout issue seems to be from the auth tokens not being persisted to the datastore like they are supposed to after a successful login. Need to debug it more to see why it isn't saving correctly.

**Comment by jeremydw** [comment]
Getting a new error this morning - "Unable to confirm authentication with GitHub". After closing the dialog I can navigate around correctly.

![image](https://user-images.githubusercontent.com/646525/128214452-567740f4-f623-40f2-a986-0a472f9f0e95.png)
